# swagger.yaml
openapi: 3.0.0
info:
  title: Orders API (Get All Order and Change Status Order)
  description: API for managing orders
  version: 1.0.0
servers:
  - url: http://localhost:3002
  - url: https://team-one.binar-project.online

paths:
  /orders:
    get:
      summary: Get user orders
      description: Retrieve all orders for the authenticated user.
      tags:
        - Orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved orders
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '500':
          description: Internal server error

  /orders/{id}/update-status:
    patch:
      summary: Update order status
      description: Update the status of an order by ID.
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the order to update
      requestBody:
        description: Order status update object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Successfully updated order status
        '422':
          description: Status not matched
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: Status not matched
        '404':
          description: Order not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        total_price:
          type: number
          format: float
          example: 100.0
        total_quantity:
          type: number
          format: float
          example: 2
        status:
          type: string
          enum: [pending, success]
          example: pending
        createdAt:
          type: string
          format: date-time
          example: 2023-01-01T00:00:00.000Z
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      properties:
        order_id:
          type: integer
          example: 1
        item_id:
          type: integer
          example: 1
        quantity:
          type: number
          format: float
          example: 1
        Item:
          type: object
          $ref: '#/components/schemas/Item'

    Item:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Item name
        description:
          type: string
          example: Item description
        image:
          type: string
          example: item.jpg
        stock:
          type: integer
          example: 10
        price:
          type: number
          format: float
          example: 50.0

    UpdateStatusRequest:
      type: object
      properties:
        status:
          type: string
          enum: [pending, success]
          example: success
